### ISSUE TITLE
Unable to login on latest client or web interface

### ISSUE THREAD

**Issue by cwc** [tapchat/tapchat#25]
I was going to test #11, so I did a fresh install from git and grabbed the latest beta version of the mobile client. I attempted to connect with the mobile client and I receive the SSH fingerprint dialog, but then receive an error message (Invalid username or password).

When I connect to the web interface and attempt to login, I get no visible error - the login box disappears and then reappears. I checked the Javascript console and it's attempting to POST to /chat/login, but getting a 401 Unauthorized response.

Server revision: ff6411175de1a5bbea223fae95462ad471e13b7f

**Comment by codebutler** [comment]
What version of node, and what OS are you running on?

**Comment by cwc** [comment]
Node v0.10.25 on Ubuntu 13.04.

**Comment by cwc** [comment]
I should probably also add that I'm not running on the default port, but I'm not behind nginx or anything like that.

**Comment by cwc** [comment]
I tested the auth route with Postman and saw that it was returning `Invalid username`. It seems to be failing to find the user in [engine.js](https://github.com/codebutler/tapchat/blob/6aa31bed985d916611db55fc5cc23225666d3d35/lib/tapchat/engine.js#L87). Is my user somehow failing to get created?

**Comment by codebutler** [comment]
I found there were some issues with cookies when upgrading from the old version. The latest commit should fix this, but if you're still having trouble can you be sure to clear cookies (or use an incognito window) to be sure that's not the issue?

**Comment by cwc** [comment]
Upgraded to the latest and tried again, seems to be working!

**Comment by athalean** [comment]
I still have this problem with the latest git version (and node v.0.10.29). After creating the first user, it still refuses connection with an Unauthorized exception.

EDIT: Found my mistake: I mistyped the password on my phone - the exception message was simply so intimidating that I didn't consider that (maybe replace it with a more soothing "Whoopsie"-style message :-))
